#!/usr/bin/env ruby
# frozen_string_literal: true

begin
  require 'bundler/setup'
  require 'rubocop_runner'
rescue LoadError
  puts "can't find rubocop in current bundle"
  exit 1
end

exit RubocopRunner.run
